version: "3.8"

services:
    nginx:
        image: nginx:1.22.1
        ports:
            -   "8080:80"
        volumes:
            -   ./docker/nginx/conf.d/:/etc/nginx/conf.d
            -   ./:/var/www
        container_name: nginx
        depends_on:
            -   app

    # PHP SERVICE
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            -   ./:/var/www

        depends_on:
            -   db
        # container_name: cloud-storage-api

    db:
        image: postgres:15.1
        restart: always
        volumes:
            - ./tmp/db:/var/lib/pgsql
        environment:
            POSTGRES_DB: cloud-storage-api
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
        ports:
            - "8030:3306"
        container_name: pgsql
